"""Bounded Hall protection regression on the exact staged high/fine revision."""
import argparse,json,hashlib,sys,runpy
from pathlib import Path
import numpy as np
import shapely
parser=argparse.ArgumentParser();parser.add_argument('--stage',type=Path,required=True);parser.add_argument('--cache',type=Path,required=True);parser.add_argument('--output',type=Path,required=True);args=parser.parse_args();P=Path(__file__).resolve().parents[1];stagepath=args.stage/'staged-partitions.json';stage=json.load(open(stagepath));validation=json.load(open(args.stage/'independent-validation.json'));sha=hashlib.sha256(stagepath.read_bytes()).hexdigest();assert validation['stageSha256']==sha and validation['status']=='pass'
sys.argv=['check','--cache',str(args.cache),'--output',str(args.cache/'corridor-base-verification.json')];ctx=runpy.run_path(str(P/'scripts/check-halls-source-protection.py'));removed=ctx['removed'];protection=ctx['protection'];m=ctx['m'];env=ctx['env'];geometry=ctx['geometry'];Heights=ctx['Heights'];ug=ctx['unary_union']([ctx['Polygon'](part['rings'][0],part['rings'][1:])for part in m['structureParts']]);baseline={t['id']:t for t in json.load(open(P/'public/models/preview-manifest.json'))['tiles']};report={'stageSha256':sha,'partitionCount':len(stage['patches']),'validatedLevelCount':validation['levelCount'],'scopeTrees':['12-NW-6C-18','12-NW-6C-19','12-NW-11A-3','12-NW-11A-4'],'levels':{}}
j=json.load(open(P/'docs/source-evidence-v4/building-quality/halls-stage-ray-audit.json'));eye=np.array(j['state'])
for level in ['high','fine']:
 triangles=[];sources=[];rows=[]
 for patch in stage['patches']:
  for tile in patch['levels'][level]['tiles']:
   if not any('/'+tree+'/'in tile['id']for tree in report['scopeTrees']):continue
   lo=tile['bounds']['min'];hi=tile['bounds']['max']
   if hi[0]<m['boundsXZ']['min'][0]or lo[0]>m['boundsXZ']['max'][0]or hi[2]<m['boundsXZ']['min'][1]or lo[2]>m['boundsXZ']['max'][1]:continue
   path=Path(tile['url']);path=path if path.is_absolute()else P/'public/models/hires'/path;assert hashlib.sha256(path.read_bytes()).hexdigest()==tile['sha256'];matrix=np.array(tile['matrix']);assert np.max(abs(matrix-np.array(baseline[tile['matrixSourceBaselineId']]['matrix'])))<1e-12
   t,_=geometry(path,matrix.reshape(4,4,order='F'));triangles.append(t);sources.append({'id':tile['id'],'url':str(path),'sha256':tile['sha256'],'originalError':tile['originalError'],'sourceMatrixBaselineId':tile['matrixSourceBaselineId'],'triangles':len(t)})
 T=np.concatenate(triangles);C=T.mean(1);N=np.cross(T[:,1]-T[:,0],T[:,2]-T[:,0]);N/=np.maximum(1e-20,np.linalg.norm(N,axis=1))[:,None];old=removed(C);preserve=protection(C,N);dtm=Heights(sorted((P/'public/terrain/source-data').glob('*.tif')))(np.column_stack([C[:,0]+844800,820500-C[:,2]]));ground=old&~shapely.contains_xy(env,C[:,0],C[:,2])&(abs(N[:,1])>=.6)&(abs(C[:,1]-dtm)<=1);ugx=old&shapely.covers(ug,shapely.points(C[:,[0,2]]));e1=T[:,1]-T[:,0];e2=T[:,2]-T[:,0];q=eye-T[:,0];s=np.cross(q,e1)
 for r in j['rays']:
  if not r['oldSourceVisible']:continue
  d=np.array(r['oldSourceVisible']['position'])-eye;d/=np.linalg.norm(d);cross=np.cross(np.broadcast_to(d,e2.shape),e2);det=np.einsum('ij,ij->i',e1,cross);safe=np.where(abs(det)>1e-10,det,np.inf);u=np.einsum('ij,ij->i',q,cross)/safe;v=s@d/safe;distance=np.einsum('ij,ij->i',e2,s)/safe;ix=np.flatnonzero((abs(det)>1e-10)&(u>=0)&(v>=0)&(u+v<=1)&(distance>0));points=eye+distance[ix,None]*d;before=~removed(points);after=before|protection(points,N[ix]);newfront=(~before)&after&(distance[ix]<r['newModelDistance']-1e-5);assert not newfront.any(),(level,r['pixel']);rows.append({'pixel':r['pixel'],'sourceIntersections':len(ix),'preexistingSourceInFront':bool((before&(distance[ix]<r['newModelDistance']-1e-5)).any()),'protectionReintroducedSourceInFront':bool(newfront.any())})
 report['levels'][level]={'sourceFiles':sources,'trianglesRead':len(T),'oldDeletedCentroids':int(old.sum()),'restoredSourceCentroids':int((old&preserve).sum()),'dtmCompatibleGroundCentroids':int(ground.sum()),'restoredGroundCentroids':int((ground&preserve).sum()),'ugxSourceCentroidsDeletedBefore':int(ugx.sum()),'ugxSourceCentroidsRestored':int((ugx&preserve).sum()),'oldWallRays':rows,'preexistingWallRayConflicts':sum(r['preexistingSourceInFront']for r in rows)}
report['status']='pass for protection regression; source LOD visual acceptance remains separate';report['limits']=['Only the four named source trees whose actual bounds intersect the current Hall support area were read.','The previous thirteen rays are reused with their recorded world direction, not attributed to the new screenshot.','Before/after differences refer to the protection predicate. A coarse-source wall already outside the deletion support before this change is reported separately, never called a regression fixed.','Ground/UG X counts are centroid classifications, not mesh area. Disconnected intervals remain partially protected.'];args.output.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({**report,'levels':{k:{a:b for a,b in v.items()if a not in ['sourceFiles','oldWallRays']}for k,v in report['levels'].items()}},indent=2))
