'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {X,Maximize,Compass} from 'lucide-react';
import {releaseObject} from './resources';
export default function StandaloneBuilding({catalogId,onClose,onIndoor}:{catalogId:string;onClose:()=>void;onIndoor:(name:string)=>void}){
 const host=useRef<HTMLDivElement>(null),controlsRef=useRef<any>(null);const [building,setBuilding]=useState<any>(null),[status,setStatus]=useState('正在读取原始逐栋外观…');
 useEffect(()=>{let dead=false,raf=0;const abort=new AbortController(),scene=new THREE.Scene(),renderer=new THREE.WebGLRenderer({antialias:true}),camera=new THREE.PerspectiveCamera(40,1,.1,2500),root=new THREE.Group();renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0xdbeaf0);renderer.outputColorSpace=THREE.SRGBColorSpace;host.current!.appendChild(renderer.domElement);scene.add(root,new THREE.HemisphereLight(0xffffff,0x628596,2));const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=15;controls.maxDistance=550;const observer=new ResizeObserver(()=>{const h=host.current;if(!h)return;renderer.setSize(h.clientWidth,h.clientHeight);camera.aspect=h.clientWidth/h.clientHeight;camera.updateProjectionMatrix()});observer.observe(host.current!);let last=0;function frame(t:number){raf=requestAnimationFrame(frame);if(t-last<30)return;last=t;controls.update();renderer.render(scene,camera)}frame(0);
 fetch('/models/standalone/manifest.json',{signal:abort.signal}).then(r=>r.json()).then(async(d:any)=>{const b=d.buildings.find((b:any)=>b.catalogId===catalogId);if(!b)throw Error('该楼暂无已核实独立外观');setBuilding(b);const gltf=await new GLTFLoader().loadAsync('/models/standalone/'+b.url);if(dead){releaseObject(gltf.scene);return}const placed=new THREE.Group();placed.position.fromArray(b.offset);placed.add(gltf.scene);root.add(placed);root.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(root),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());root.position.copy(center).multiplyScalar(-1);
 gltf.scene.traverse((o:any)=>{if(!o.isMesh)return;const array=Array.isArray(o.material),materials=(array?o.material:[o.material]).map((m:any)=>{if(m.map){m.map.generateMipmaps=false;m.map.minFilter=THREE.LinearFilter;m.map.anisotropy=4}const next=new THREE.MeshBasicMaterial({map:m.map,color:m.color,side:THREE.DoubleSide});m.dispose();return next});o.material=array?materials:materials[0]});
 const extent=Math.max(size.x,size.z,size.y);const home=(top=false)=>{controls.target.set(0,0,0);camera.position.set(top?0:extent*1.1,top?extent*2:extent*.8,top?.01:extent*1.4);controls.update()};controlsRef.current={home};home();setStatus('原始逐栋模型已载入');}).catch(e=>{if(!dead)setStatus(String(e))});return()=>{dead=true;abort.abort();cancelAnimationFrame(raf);observer.disconnect();controls.dispose();releaseObject(root);renderer.dispose();host.current?.replaceChildren();controlsRef.current=null}},[catalogId]);
 return <div className="standalone-modal" role="dialog" aria-modal="true" aria-label="独立建筑外观"><div className="standalone-viewport" ref={host}/><header><div><span className="eyebrow">政府公开逐栋模型 · 原始纹理</span><h2>{building?.label||'建筑外观'}</h2><p>拖动旋转 · 滚轮放大 · 双指平移</p></div><button className="icon" aria-label="关闭独立外观" onClick={onClose}><X size={22}/></button></header><div className="standalone-controls"><button className="icon" aria-label="复位独立建筑" onClick={()=>controlsRef.current?.home()}><Maximize size={19}/></button><button className="icon" aria-label="独立建筑俯视" onClick={()=>controlsRef.current?.home(true)}><Compass size={19}/></button></div><aside><button className="pano-return" onClick={onClose}>← 返回校园原视角</button><h3>从外观进入楼内</h3><p>单独旋转这栋建筑，查看被邻楼遮挡的外墙与入口形态。</p><button className="enter-indoor" onClick={()=>onIndoor(catalogId==='campus-22'?'Shaw Auditorium':'Cheng Yu Tung Building')}>浏览对应室内楼层 →</button><details><summary>模型来源与日期</summary><p>Individualised Models，Lands Department。源包修订2026-04-24，不代表本栋拍摄日期。保留原纹理和矩阵，仅移动至共同原点。</p><a href="/models/standalone/manifest.json" target="_blank" rel="noreferrer">查看逐项来源</a></details></aside><footer role="status">{status} · 独立外观模式保留校园原视角</footer></div>
}
