import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {releaseObject,releaseTexture} from './resources';
export type Quality='light'|'auto'|'detail';
type Binding={material:THREE.MeshBasicMaterial;low:THREE.Texture;source:any;tile:any};
export class DetailStream{
 quality:Quality='auto';terrainLimit=8;dead=false;active=true;bindings:Binding[]=[];catalog=new Map<string,any>();pool=new Map<string,{texture:THREE.Texture;bytes:number}>();pending=new Map<string,AbortController>();wanted=new Set<string>();errors=0;terrainTiles:any[]=[];terrainObjects=new Map<string,THREE.Object3D>();terrainPending=new Map<string,AbortController>();terrainWanted=new Set<string>();group=new THREE.Group();last=0;loadedBytes=0;mask={count:{value:0},rects:{value:Array.from({length:8},()=>new THREE.Vector4())}};
 constructor(public scene:THREE.Scene,public camera:THREE.PerspectiveCamera,public target:THREE.Vector3,public renderer:THREE.WebGLRenderer){scene.add(this.group)}
 async init(){const [t,r]:any[]=await Promise.all([fetch('/models/texture-detail-manifest.json').then(r=>r.json()),fetch('/terrain/detail/manifest.json').then(r=>r.ok?r.json():{tiles:[]}).catch(()=>({tiles:[]}))]);if(this.dead)return;for(const v of t.tiles)this.catalog.set(v.id,v);this.terrainTiles=r.tiles||[]}
 register(id:string,m:THREE.MeshBasicMaterial,materialIndex:number){const tile=this.catalog.get(id),source=tile?.materials[String(materialIndex)];if(m.map&&source)this.bindings.push({material:m,low:m.map,source,tile})}
 setCoarse(root:THREE.Object3D){root.traverse((o:any)=>{if(!o.material)return;for(const m of(Array.isArray(o.material)?o.material:[o.material])){m.onBeforeCompile=(shader:any)=>{shader.uniforms.detailCount=this.mask.count;shader.uniforms.detailRects=this.mask.rects;shader.vertexShader='varying vec2 vDetailXZ;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvDetailXZ=(modelMatrix*vec4(position,1.0)).xz;');shader.fragmentShader='varying vec2 vDetailXZ; uniform int detailCount; uniform vec4 detailRects[8];\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <clipping_planes_fragment>','#include <clipping_planes_fragment>\nfor(int k=0;k<8;k++){if(k>=detailCount)break;vec4 b=detailRects[k];if(vDetailXZ.x>=b.x&&vDetailXZ.x<=b.z&&vDetailXZ.y>=b.y&&vDetailXZ.y<=b.w)discard;}')};m.needsUpdate=true}})}
 updateMask(){let i=0;for(const t of this.terrainTiles)if(this.terrainObjects.has(t.id)&&i<8){this.mask.rects.value[i++].set(t.bounds.min[0],t.bounds.min[2],t.bounds.max[0],t.bounds.max[2])}this.mask.count.value=i}
 setQuality(q:Quality){this.quality=q;this.last=0;this.update(true)}
 update(force=false,geometry=true,terrain=true){if(this.dead)return;const now=performance.now();if(!force&&now-this.last<550)return;this.last=now;
 const distance=this.camera.position.distanceTo(this.target),enabled=this.active&&this.quality!=='light';const detailed=enabled&&distance<950;
 const maxBytes=(this.quality==='detail'?192:96)*1024*1024,maxTiles=this.quality==='detail'?24:12;
 const frustum=new THREE.Frustum().setFromProjectionMatrix(new THREE.Matrix4().multiplyMatrices(this.camera.projectionMatrix,this.camera.matrixWorldInverse));
 const candidates=geometry&&detailed?[...this.catalog.values()].filter(t=>frustum.intersectsBox(new THREE.Box3(new THREE.Vector3(...t.bounds.min as [number,number,number]),new THREE.Vector3(...t.bounds.max as [number,number,number])))).sort((a,b)=>Math.hypot(a.center[0]-this.target.x,a.center[2]-this.target.z)-Math.hypot(b.center[0]-this.target.x,b.center[2]-this.target.z)):[];
 let bytes=0,tiles=0;this.wanted=new Set();for(const tile of candidates){if(tiles>=maxTiles)break;const images=Object.values(tile.materials) as any[];let extra=0;const unique=new Map<string,any>();for(const im of images)if(Math.max(im.width,im.height)>512&&!this.wanted.has(im.url))unique.set(im.url,im);for(const im of unique.values())extra+=im.decodedBytes;if(bytes+extra>maxBytes)continue;bytes+=extra;tiles++;for(const url of unique.keys())this.wanted.add(url)}
 for(const b of this.bindings){const loaded=this.wanted.has(b.source.url)?this.pool.get(b.source.url):null;const next=loaded?.texture||b.low;if(b.material.map!==next){b.material.map=next;b.material.needsUpdate=true}}
 for(const [url,item] of this.pool)if(!this.wanted.has(url)){releaseTexture(item.texture);this.pool.delete(url)}
 for(const [url,controller] of this.pending)if(!this.wanted.has(url)){controller.abort();this.pending.delete(url)}
 for(const b of this.bindings)if(this.wanted.has(b.source.url)&&!this.pool.has(b.source.url)&&!this.pending.has(b.source.url)&&this.pending.size<2)this.loadTexture(b.source);
 const terrainLimit=this.terrainLimit;
 this.terrainWanted=new Set(terrain&&detailed?this.terrainTiles.filter(t=>Math.hypot(t.center[0]-this.target.x,t.center[2]-this.target.z)<600).sort((a,b)=>Math.hypot(a.center[0]-this.target.x,a.center[2]-this.target.z)-Math.hypot(b.center[0]-this.target.x,b.center[2]-this.target.z)).slice(0,terrainLimit).map(t=>t.id):[]);
 this.group.visible=terrain;
 for(const [id,o] of this.terrainObjects)if(!this.terrainWanted.has(id)){this.group.remove(o);releaseObject(o);this.terrainObjects.delete(id)}this.updateMask();
 for(const [id,c] of this.terrainPending)if(!this.terrainWanted.has(id)){c.abort();this.terrainPending.delete(id)}
 for(const t of this.terrainTiles)if(this.terrainWanted.has(t.id)&&!this.terrainObjects.has(t.id)&&!this.terrainPending.has(t.id)&&this.terrainPending.size<1)this.loadTerrain(t);
 }
 async loadTexture(source:any){const c=new AbortController();this.pending.set(source.url,c);try{const r=await fetch(source.url,{signal:c.signal});if(!r.ok)throw Error('原纹理加载失败');const blob=await r.blob(),bitmap=await createImageBitmap(blob,{imageOrientation:'none',premultiplyAlpha:'none'});if(this.dead||c.signal.aborted||!this.wanted.has(source.url)){bitmap.close();return}const texture=new THREE.Texture(bitmap);texture.flipY=false;texture.colorSpace=THREE.SRGBColorSpace;texture.generateMipmaps=false;texture.minFilter=THREE.LinearFilter;texture.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());texture.needsUpdate=true;this.pool.set(source.url,{texture,bytes:source.decodedBytes});this.loadedBytes+=source.bytes;for(const b of this.bindings)if(b.source.url===source.url){b.material.map=texture;b.material.needsUpdate=true}}catch(e){if(!c.signal.aborted)this.errors++}finally{if(this.pending.get(source.url)===c)this.pending.delete(source.url);this.last=0}}
 async loadTerrain(tile:any){const c=new AbortController();this.terrainPending.set(tile.id,c);try{const url=tile.url.startsWith('/')?tile.url:'/terrain/detail/'+tile.url;const r=await fetch(url,{signal:c.signal});if(!r.ok)throw Error('细地形加载失败');const gltf=await new GLTFLoader().parseAsync(await r.arrayBuffer(),'/terrain/detail/');if(this.dead||c.signal.aborted||!this.terrainWanted.has(tile.id)){releaseObject(gltf.scene);return}gltf.scene.traverse((o:any)=>{if(o.isMesh){o.material.polygonOffset=true;o.material.polygonOffsetFactor=0;o.material.polygonOffsetUnits=0}});this.terrainObjects.set(tile.id,gltf.scene);this.group.add(gltf.scene);this.updateMask();this.loadedBytes+=tile.bytes||0}catch(e){if(!c.signal.aborted)this.errors++}finally{if(this.terrainPending.get(tile.id)===c)this.terrainPending.delete(tile.id);this.last=0}}
 stats(){return {quality:this.quality,originalTextures:this.pool.size,originalTextureMiB:+([...this.pool.values()].reduce((n,p)=>n+p.bytes,0)/1048576).toFixed(1),terrainTiles:this.terrainObjects.size,terrainTriangles:this.terrainTiles.filter(t=>this.terrainObjects.has(t.id)).reduce((s,t)=>s+(t.triangles||0),0),pending:this.pending.size+this.terrainPending.size,errors:this.errors,downloadMiB:+(this.loadedBytes/1048576).toFixed(1)}}
 dispose(){this.dead=true;for(const c of [...this.pending.values(),...this.terrainPending.values()])c.abort();for(const b of this.bindings)b.material.map=b.low;for(const item of this.pool.values())releaseTexture(item.texture);this.pool.clear();releaseObject(this.group);this.scene.remove(this.group);this.bindings=[]}
}
